<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DimPerson;

class DimPersonSeeder extends Seeder
{
    private $people = [
        [
           "id"=>"1",
           "prinom"=>"Egdumar",
           "segnom"=>"",
           "priape"=>"Chavez",
           "segape"=>"Arana"
        ],
        [
           "id"=>"2",
           "prinom"=>"Juan",
           "segnom"=>"Alfredo",
           "priape"=>"Quenza",
           "segape"=>""
        ],
        [
           "id"=>"3",
           "prinom"=>"Camilo",
           "segnom"=>"Andres",
           "priape"=>"Gonzalez",
           "segape"=>""
        ],
        [
           "id"=>"4",
           "prinom"=>"Wilson",
           "segnom"=>"Hernando",
           "priape"=>"Perez",
           "segape"=>""
        ],
        [
           "id"=>"5",
           "prinom"=>"Yomar",
           "segnom"=>"Asdrubal",
           "priape"=>"Reyes",
           "segape"=>""
        ],
        [
           "id"=>"6",
           "prinom"=>"William",
           "segnom"=>"Paul",
           "priape"=>"Leon",
           "segape"=>"Roa"
        ],
        [
           "id"=>"7",
           "prinom"=>"Jose",
           "segnom"=>"Hernando",
           "priape"=>"Gonzalez",
           "segape"=>""
        ],
        [
           "id"=>"8",
           "prinom"=>"Oscar",
           "segnom"=>"",
           "priape"=>"Mariño",
           "segape"=>"Montaño"
        ],
        [
           "id"=>"9",
           "prinom"=>"Andres",
           "segnom"=>"",
           "priape"=>"Padilla",
           "segape"=>"Avila"
        ],
        [
           "id"=>"10",
           "prinom"=>"Ehiana",
           "segnom"=>"",
           "priape"=>"Galeano",
           "segape"=>"Reyes"
        ],
        [
           "id"=>"11",
           "prinom"=>"Roger",
           "segnom"=>"Alcides",
           "priape"=>"Cisneros",
           "segape"=>""
        ],
        [
           "id"=>"12",
           "prinom"=>"Dumar",
           "segnom"=>"Jose",
           "priape"=>"Quintero",
           "segape"=>""
        ],
        [
           "id"=>"13",
           "prinom"=>"Juan",
           "segnom"=>"Carlos",
           "priape"=>"Castañeda",
           "segape"=>""
        ],
        [
           "id"=>"14",
           "prinom"=>"Manuel",
           "segnom"=>"",
           "priape"=>"Calderon",
           "segape"=>""
        ],
        [
           "id"=>"15",
           "prinom"=>"Manuel",
           "segnom"=>"",
           "priape"=>"Perez",
           "segape"=>""
        ],
        [
           "id"=>"16",
           "prinom"=>"Julieth",
           "segnom"=>"",
           "priape"=>"Jimenez",
           "segape"=>""
        ],
        [
           "id"=>"17",
           "prinom"=>"Clara",
           "segnom"=>"",
           "priape"=>"Godoy",
           "segape"=>""
        ],
        [
           "id"=>"18",
           "prinom"=>"Miguel",
           "segnom"=>"",
           "priape"=>"Hernandez",
           "segape"=>""
        ],
        [
           "id"=>"19",
           "prinom"=>"Renson",
           "segnom"=>"",
           "priape"=>"Martinez",
           "segape"=>""
        ],
        [
           "id"=>"20",
           "prinom"=>"Albeiro",
           "segnom"=>"",
           "priape"=>"Vanegas",
           "segape"=>""
        ],
        [
           "id"=>"21",
           "prinom"=>"Nixon",
           "segnom"=>"",
           "priape"=>"Barreño",
           "segape"=>""
        ],
        [
           "id"=>"22",
           "prinom"=>"Juan",
           "segnom"=>"Pablo",
           "priape"=>"Jimenez",
           "segape"=>""
        ],
        [
           "id"=>"23",
           "prinom"=>"Ivan",
           "segnom"=>"Dario",
           "priape"=>"Gomez",
           "segape"=>""
        ],
        [
           "id"=>"24",
           "prinom"=>"Votos",
           "segnom"=>"",
           "priape"=>"en Blanco",
           "segape"=>""
        ],
        [
           "id"=>"25",
           "prinom"=>"Votos",
           "segnom"=>"",
           "priape"=>"Nulos",
           "segape"=>""
        ],
        [
           "id"=>"26",
           "prinom"=>"Votos",
           "segnom"=>"",
           "priape"=>"No Marcados",
           "segape"=>""
        ],
        [
           "id"=>"27",
           "prinom"=>"Total",
           "segnom"=>"",
           "priape"=>"Votos",
           "segape"=>""
        ]
     ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->people as $person){
            DimPerson::create([
                "id"=>$person['id'],
                "first_name"=>$person['prinom'],
                "second_name"=>$person['segnom'],
                "first_last_name"=>$person['priape'],
                "second_last_name"=>$person['segape']
            ]);
        }
    }
}
